version: '3'

services:
  web:
    image: alfabet
    command: uvicorn main:app --host 0.0.0.0 --port 80
    container_name: alfabet-app
    ports:
      - 80:80
    environment:
      - db_host=db:5432
    depends_on:
      - db

  db:
    image: postgis/postgis
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=alfabet
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"